# Use Codecov in "informational" mode: post coverage results to pull requests,
# but do not report a failing status if the coverage decreases.
#
# FIXME: remove this when we have a much higher coverage fraction.
coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
