name: Strip Python sources
description: Replace Python source code with byte code where possible
inputs:
  args:
    description: Arguments to pass to script
    default: '.'
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
    - run: python "${{ github.action_path }}/strip-python.py" ${{ inputs.args }}
      shell: bash
