name: QEMU test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hydrate:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      options: --platform linux/arm64
    steps:
      - run: uname -a
