name: QEMU test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hydrate:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      options: --platform 
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: uname -a
        run: docker run --rm --platform linux/arm64 python:3.11 uname -a
