name: QEMU test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hydrate:
    runs-on: ubuntu-latest
    steps:
      - name: uname -a
        run: docker run --rm --platform linux/arm64 python:3.11 uname -a
